trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Create NuPkg
  inputs:
    command: pack
    packagesToPack: Toxon.Swim/Toxon.Swim.csproj
    configuration: '$(buildConfiguration)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
- task: DotNetCoreCLI@2
  displayName: Publish to internal feed
  inputs:
    command: push
    publishVstsFeed: 'Toxon.Swim'
- task: PublishBuildArtifacts@1
